### ISSUE TITLE
Markdown test

### ISSUE THREAD

**Issue by Szelemetko** [Szelemetko/giflib-hibernate-treehouse#2]
## TODO

*Italics testing*

* [] List element unselected nr 1
* [] List element unselected nr 2
* [x] Lise element selected nr 3

:tada: :ok_woman: 🎊 
cc @szelemetko
